### ISSUE TITLE
Asymmetric features in sim 22° halo

### ISSUE THREAD

**Issue by XuebingZhao** [LoveDaisy/ice_halo_sim#1] opened 2018-07-17 17:32 UTC
When I use pure randomly distributed hex cylinders to simulate the commonly 22° halo, there are some asymmetric arcs and features in the image, as shown bellow. This is hard to explain.
![img](https://user-images.githubusercontent.com/19829490/42834819-46e70434-8a2a-11e8-9428-a0ee47d6970b.jpg)
.

**Comment by LoveDaisy** [comment] 2018-07-23 06:08
This issue cannot be reproduced on my computer. Could you show your settings for that simulation? I guess it could be a rendering problem.

**Comment by XuebingZhao** [comment] 2018-07-23 09:30
This is my configure file:
[Issue-config.zip](https://github.com/LoveDaisy/ice_halo_sim/files/2218733/Issue-config.zip)

**Comment by LoveDaisy** [comment] 2018-07-23 13:45
Still it cannot be reproduced on my computer. I highly recommend you update your code to the latest version. Maybe it is caused by a minor bug and I have fixed it several commits before.

I'm still developing on this project. And codes are going better and better.

**Comment by LoveDaisy** [comment] 2018-07-23 13:48
Issue closed.

Please feel free to comment here if still any strange arcs appear on your render result. I'll reopen this issue then.

**Comment by XuebingZhao** [comment] 2018-07-23 18:14
Maybe here is a reason: these arcs occurred only when I use`cmake -D CMAKE_BUILD_TYPE=release`.
However, there are still some very dim lines which can be n
oticed when the build type was not specified. The image below is rendered in 30M lights.
Here is the cmake output on screen:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenCV: /usr/local (found version "3.4.2") found components:  core imgproc imgcodecs
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stevenzhao/ice_halo_sim/cpp/build
```

![Uploading img.jpg…]()

**Comment by XuebingZhao** [comment] 2018-07-23 18:46
I also confirmed that this issue is located in Sim not Render

**Comment by XuebingZhao** [comment] 2018-07-23 21:05
After edited flag -O3 to -O2, -O1 and -O0 in CMakeList, I found that -O1 to -O3 lead to same result (and  similar time). -O0 is better but spends doubled time.

**Comment by LoveDaisy** [comment] 2018-07-24 08:38
Well..., interesting...
I tried again and rendered with intensity of 10.0, and I confirmed there were strange arcs. Seems much fainter than your case.
I'm trying to figure out why.

Issue reopened.

**Comment by LoveDaisy** [comment] 2018-07-24 08:41
Here is my result. FYI.
![img](https://user-images.githubusercontent.com/4991230/43126760-361002c4-8f60-11e8-8b5c-89d8770e2081.jpg)
It looks much fainter than yours.

**Comment by XuebingZhao** [comment] 2018-07-24 12:50
These arcs are also fainter in my color image. 
Rounding error?

**Comment by LoveDaisy** [comment] 2019-02-21 05:15
@XuebingZhao I have made major refactors recently. It seems all right with your case now. So I decide to close the issue. If there is still problem, pls comment here and I'll reopen it.

**Closed** 2019-02-21 05:16 UTC
